version: '3.3'

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  
  pgadmin:  
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
  
  mysql:
    image: mysql:8  
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=my_base
      - MYSQL_USER= root
      - MYSQL_ROOT_PASSWORD= admin123ADMIN
      - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
      - ~/docker/mysql-data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - PMA_HOST=mysql
    ports:
      - 8080:80
